from . import consonants, vowels

VOWEL_GLYPHS = vowels.VOWEL_GLYPHS
CONSONANT_GLYPHS = consonants.CONSONANT_GLYPHS

VOWEL_CLASSES = vowels.VOWEL_CLASSES
CONSONANT_CLASSES = consonants.CONSONANT_CLASSES
